server:
  port: 40010
spring:
  r2dbc:
    username: root
    password: 123456
    url: r2dbcs:mysql://116.62.17.98:4306/fchat
  data:
    mongodb:
      username: fchat
      password: "123456"
      host: 116.62.17.98
      database: fchat
      port: 27017
  redis:
    port: 7379
    host: 116.62.17.98
    password: 123456
    database: 3
fchat:
  noneCertificationUrl:
    - POST:/user
    - POST:/user/register
    - GET:/test/limit
    - GET:/test/insert
  seaweedFs:
    url: https://fs.mini2436.xyz
    windowsTempFilePath: C:\\Users\\58499\\projects\\idea-project\\fchat-server\\temp\\
    linuxTempFilePath: /temp/
  system:
    tokenName: f-token
    encryptionKey: BQEW4'ZGy|4@Xl85k1,MxcWkvJu?)wNu
    tokenKey: D'Sq5Rs7^aLuM'G$Tou_.Xu%d/s3Dw%l
    tokenExpiredTime: 86400000